export const Element = Object.freeze({
    FIRE: "fire",
    ICE: "ice",
    THUNDER: "thunder",
    EARTH: "earth",
    POISON: "poison",
    WATER: "water",
    WIND: "wind",
    HOLY: "holy",
    NONE: "none"
});

export const ALL_CARDS = [
    {
        "id": 0,
        "name": "hidden_card",
        "numbers": ["A", "A", "A", "A"],
        "element": Element.NONE,
        "level": 1,
    },
    {
        "id": 1,
        "name": "Geezard",
        "numbers": [1, 5, 4, 1],
        "element": Element.NONE,
        "level": 1,
    },
    {
        "id": 2,
        "name": "Funguar",
        "numbers": [5, 3, 1, 1],
        "element": Element.NONE,
        "level": 1,
    },
    {
        "id": 3,
        "name": "Bite Bug",
        "numbers": [1, 5, 3, 3],
        "element": Element.NONE,
        "level": 1,
    },
    {
        "id": 4,
        "name": "Red Bat",
        "numbers": [6, 2, 1, 1],
        "element": Element.NONE,
        "level": 1,
    },
    {
        "id": 5,
        "name": "Blobra",
        "numbers": [2, 5, 3, 1],
        "element": Element.NONE,
        "level": 1,
    },
    {
        "id": 6,
        "name": "Gayla",
        "numbers": [2, 4, 1, 4],
        "element": Element.THUNDER,
        "level": 1,
    },
    {
        "id": 7,
        "name": "Gesper",
        "numbers": [1, 1, 5, 4],
        "element": Element.NONE,
        "level": 1,
    },
    {
        "id": 8,
        "name": "Fastitocalon-F",
        "numbers": [3, 1, 5, 2],
        "element": Element.EARTH,
        "level": 1,
    },
    {
        "id": 9,
        "name": "Blood Soul",
        "numbers": [2, 1, 1, 6],
        "element": Element.NONE,
        "level": 1,
    },
    {
        "id": 10,
        "name": "Caterchipillar",
        "numbers": [4, 3, 2, 4],
        "element": Element.NONE,
        "level": 1,
    },
    {
        "id": 11,
        "name": "Cockatrice",
        "numbers": [2, 6, 1, 2],
        "element": Element.THUNDER,
        "level": 1,
    },
    {
        "id": 12,
        "name": "Grat",
        "numbers": [7, 1, 1, 3],
        "element": Element.NONE,
        "level": 2,
    },
    {
        "id": 13,
        "name": "Buel",
        "numbers": [6, 3, 2, 2],
        "element": Element.NONE,
        "level": 2,
    },
    {
        "id": 14,
        "name": "Mesmerize",
        "numbers": [5, 4, 3, 3],
        "element": Element.NONE,
        "level": 2,
    },
    {
        "id": 15,
        "name": "Glacial Eye",
        "numbers": [6, 3, 1, 4],
        "element": Element.ICE,
        "level": 2,
    },
    {
        "id": 16,
        "name": "Belhelmel",
        "numbers": [3, 3, 4, 5],
        "element": Element.NONE,
        "level": 2,
    },
    {
        "id": 17,
        "name": "Thrustaevis",
        "numbers": [5, 5, 3, 2],
        "element": Element.WIND,
        "level": 2,
    },
    {
        "id": 18,
        "name": "Anacondaur",
        "numbers": [5, 5, 1, 3],
        "element": Element.POISON,
        "level": 2,
    },
    {
        "id": 19,
        "name": "Creeps",
        "numbers": [5, 2, 2, 5],
        "element": Element.THUNDER,
        "level": 2,
    },
    {
        "id": 20,
        "name": "Grendel",
        "numbers": [4, 2, 4, 5],
        "element": Element.THUNDER,
        "level": 2,
    },
    {
        "id": 21,
        "name": "Jelleye",
        "numbers": [3, 7, 2, 1],
        "element": Element.NONE,
        "level": 2,
    },
    {
        "id": 22,
        "name": "Grand Mantis",
        "numbers": [5, 3, 2, 5],
        "element": Element.NONE,
        "level": 2,
    },
    {
        "id": 23,
        "name": "Forbidden",
        "numbers": [6, 2, 6, 3],
        "element": Element.NONE,
        "level": 3,
    },
    {
        "id": 24,
        "name": "Armadodo",
        "numbers": [6, 6, 3, 1],
        "element": Element.EARTH,
        "level": 3,
    },
    {
        "id": 25,
        "name": "Tri-Face",
        "numbers": [3, 5, 5, 5],
        "element": Element.POISON,
        "level": 3,
    },
    {
        "id": 26,
        "name": "Fastitocalon",
        "numbers": [7, 3, 5, 1],
        "element": Element.EARTH,
        "level": 3,
    },
    {
        "id": 27,
        "name": "Snow Lion",
        "numbers": [7, 3, 1, 5],
        "element": Element.ICE,
        "level": 3,
    },
    {
        "id": 28,
        "name": "Ochu",
        "numbers": [5, 3, 6, 3],
        "element": Element.NONE,
        "level": 3,
    },
    {
        "id": 29,
        "name": "SAM08G",
        "numbers": [5, 4, 6, 2],
        "element": Element.FIRE,
        "level": 3,
    },
    {
        "id": 30,
        "name": "Death Claw",
        "numbers": [4, 2, 4, 7],
        "element": Element.FIRE,
        "level": 3,
    },
    {
        "id": 31,
        "name": "Cactuar",
        "numbers": [6, 3, 2, 6],
        "element": Element.NONE,
        "level": 3,
    },
    {
        "id": 32,
        "name": "Tonberry",
        "numbers": [3, 4, 6, 4],
        "element": Element.NONE,
        "level": 3,
    },
    {
        "id": 33,
        "name": "Abyss Worm",
        "numbers": [7, 5, 2, 3],
        "element": Element.EARTH,
        "level": 3,
    },
    {
        "id": 34,
        "name": "Turtapod",
        "numbers": [2, 7, 3, 6],
        "element": Element.NONE,
        "level": 4,
    },
    {
        "id": 35,
        "name": "Vysage",
        "numbers": [6, 5, 5, 4],
        "element": Element.NONE,
        "level": 4,
    },
    {
        "id": 36,
        "name": "T-Rexaur",
        "numbers": [4, 7, 6, 2],
        "element": Element.NONE,
        "level": 4,
    },
    {
        "id": 37,
        "name": "Bomb",
        "numbers": [2, 3, 7, 6],
        "element": Element.FIRE,
        "level": 4,
    },
    {
        "id": 38,
        "name": "Blitz",
        "numbers": [1, 7, 6, 4],
        "element": Element.THUNDER,
        "level": 4,
    },
    {
        "id": 39,
        "name": "Wendigo",
        "numbers": [7, 6, 3, 1],
        "element": Element.NONE,
        "level": 4,
    },
    {
        "id": 40,
        "name": "Torama",
        "numbers": [7, 4, 4, 4],
        "element": Element.NONE,
        "level": 4,
    },
    {
        "id": 41,
        "name": "Imp",
        "numbers": [3, 6, 7, 3],
        "element": Element.NONE,
        "level": 4,
    },
    {
        "id": 42,
        "name": "Blue Dragon",
        "numbers": [6, 3, 2, 7],
        "element": Element.POISON,
        "level": 4,
    },
    {
        "id": 43,
        "name": "Adamantoise",
        "numbers": [4, 6, 5, 5],
        "element": Element.EARTH,
        "level": 4,
    },
    {
        "id": 44,
        "name": "Hexadragon",
        "numbers": [7, 3, 5, 4],
        "element": Element.FIRE,
        "level": 4,
    },
    {
        "id": 45,
        "name": "Iron Giant",
        "numbers": [6, 5, 5, 6],
        "element": Element.NONE,
        "level": 5,
    },
    {
        "id": 46,
        "name": "Behemoth",
        "numbers": [3, 7, 6, 5],
        "element": Element.NONE,
        "level": 5,
    },
    {
        "id": 47,
        "name": "Chimera",
        "numbers": [7, 3, 6, 5],
        "element": Element.WATER,
        "level": 5,
    },
    {
        "id": 48,
        "name": "PuPu",
        "numbers": [3, 1, "A", 2],
        "element": Element.NONE,
        "level": 5,
    },
    {
        "id": 49,
        "name": "Elastoid",
        "numbers": [6, 7, 2, 6],
        "element": Element.NONE,
        "level": 5,
    },
    {
        "id": 50,
        "name": "GIM47N",
        "numbers": [5, 4, 5, 7],
        "element": Element.NONE,
        "level": 5,
    },
    {
        "id": 51,
        "name": "Malboro",
        "numbers": [7, 2, 7, 4],
        "element": Element.POISON,
        "level": 5,
    },
    {
        "id": 52,
        "name": "Ruby Dragon",
        "numbers": [7, 4, 2, 7],
        "element": Element.FIRE,
        "level": 5,
    },
    {
        "id": 53,
        "name": "Elnoyle",
        "numbers": [5, 6, 3, 7],
        "element": Element.NONE,
        "level": 5,
    },
    {
        "id": 54,
        "name": "Tonberry King",
        "numbers": [4, 4, 6, 7],
        "element": Element.NONE,
        "level": 5,
    },
    {
        "id": 55,
        "name": "Wedge, Biggs",
        "numbers": [6, 7, 6, 2],
        "element": Element.NONE,
        "level": 5,
    },
    {
        "id": 56,
        "name": "Fujin Raijin",
        "numbers": [2, 4, 8, 8],
        "element": Element.NONE,
        "level": 6,
    },
    {
        "id": 57,
        "name": "Elvoret",
        "numbers": [7, 4, 8, 3],
        "element": Element.WIND,
        "level": 6,
    },
    {
        "id": 58,
        "name": "X-ATM092",
        "numbers": [4, 3, 8, 7],
        "element": Element.NONE,
        "level": 6,
    },
    {
        "id": 59,
        "name": "Granaldo",
        "numbers": [7, 5, 2, 8],
        "element": Element.NONE,
        "level": 6,
    },
    {
        "id": 60,
        "name": "Gerogero",
        "numbers": [1, 3, 8, 8],
        "element": Element.POISON,
        "level": 6,
    },
    {
        "id": 61,
        "name": "Iguion",
        "numbers": [8, 2, 2, 8],
        "element": Element.NONE,
        "level": 6,
    },
    {
        "id": 62,
        "name": "Abadon",
        "numbers": [6, 5, 8, 4],
        "element": Element.NONE,
        "level": 6,
    },
    {
        "id": 63,
        "name": "Trauma",
        "numbers": [4, 6, 8, 5],
        "element": Element.NONE,
        "level": 6,
    },
    {
        "id": 64,
        "name": "Oilboyle",
        "numbers": [1, 8, 8, 4],
        "element": Element.NONE,
        "level": 6,
    },
    {
        "id": 65,
        "name": "Shumi",
        "numbers": [6, 4, 5, 8],
        "element": Element.NONE,
        "level": 6,
    },
    {
        "id": 66,
        "name": "Krysta",
        "numbers": [7, 1, 5, 8],
        "element": Element.NONE,
        "level": 6,
    },
    {
        "id": 67,
        "name": "Propagator",
        "numbers": [8, 8, 4, 4],
        "element": Element.NONE,
        "level": 7,
    },
    {
        "id": 68,
        "name": "Jumbo Cactuar",
        "numbers": [8, 4, 8, 4],
        "element": Element.NONE,
        "level": 7,
    },
    {
        "id": 69,
        "name": "Tri-Point",
        "numbers": [8, 8, 5, 2],
        "element": Element.THUNDER,
        "level": 7,
    },
    {
        "id": 70,
        "name": "Gargantua",
        "numbers": [5, 8, 6, 6],
        "element": Element.NONE,
        "level": 7,
    },
    {
        "id": 71,
        "name": "Mobile Type 8",
        "numbers": [8, 3, 6, 7],
        "element": Element.NONE,
        "level": 7,
    },
    {
        "id": 72,
        "name": "Sphinxara",
        "numbers": [8, 8, 3, 5],
        "element": Element.NONE,
        "level": 7,
    },
    {
        "id": 73,
        "name": "Tiamat",
        "numbers": [8, 4, 8, 5],
        "element": Element.NONE,
        "level": 7,
    },
    {
        "id": 74,
        "name": "BGH251F2",
        "numbers": [5, 5, 7, 8],
        "element": Element.NONE,
        "level": 7,
    },
    {
        "id": 75,
        "name": "Red Giant",
        "numbers": [6, 7, 8, 4],
        "element": Element.NONE,
        "level": 7,
    },
    {
        "id": 76,
        "name": "Catoblepas",
        "numbers": [1, 7, 8, 7],
        "element": Element.NONE,
        "level": 7,
    },
    {
        "id": 77,
        "name": "Ultima Weapon",
        "numbers": [7, 8, 7, 2],
        "element": Element.NONE,
        "level": 7,
    },
    {
        "id": 78,
        "name": "Chubby Chocobo",
        "numbers": [4, 9, 4, 8],
        "element": Element.NONE,
        "level": 8,
    },
    {
        "id": 79,
        "name": "Angelo",
        "numbers": [9, 3, 6, 7],
        "element": Element.NONE,
        "level": 8,
    },
    {
        "id": 80,
        "name": "Gilgamesh",
        "numbers": [3, 6, 7, 9],
        "element": Element.NONE,
        "level": 8,
    },
    {
        "id": 81,
        "name": "MiniMog",
        "numbers": [9, 2, 3, 9],
        "element": Element.NONE,
        "level": 8,
    },
    {
        "id": 82,
        "name": "Chicobo",
        "numbers": [9, 4, 4, 8],
        "element": Element.NONE,
        "level": 8,
    },
    {
        "id": 83,
        "name": "Quezacotl",
        "numbers": [2, 4, 9, 9],
        "element": Element.THUNDER,
        "level": 8,
    },
    {
        "id": 84,
        "name": "Shiva",
        "numbers": [6, 9, 7, 4],
        "element": Element.ICE,
        "level": 8,
    },
    {
        "id": 85,
        "name": "Ifrit",
        "numbers": [9, 8, 6, 2],
        "element": Element.FIRE,
        "level": 8,
    },
    {
        "id": 86,
        "name": "Siren",
        "numbers": [8, 2, 9, 6],
        "element": Element.NONE,
        "level": 8,
    },
    {
        "id": 87,
        "name": "Sacred",
        "numbers": [5, 9, 1, 9],
        "element": Element.EARTH,
        "level": 8,
    },
    {
        "id": 88,
        "name": "Minotaur",
        "numbers": [9, 9, 5, 2],
        "element": Element.EARTH,
        "level": 8,
    },
    {
        "id": 89,
        "name": "Carbuncle",
        "numbers": [8, 4, 4, "A"],
        "element": Element.NONE,
        "level": 9,
    },
    {
        "id": 90,
        "name": "Diablos",
        "numbers": [5, 3, "A", 8],
        "element": Element.NONE,
        "level": 9,
    },
    {
        "id": 91,
        "name": "Leviathan",
        "numbers": [7, 7, "A", 1],
        "element": Element.WATER,
        "level": 9,
    },
    {
        "id": 92,
        "name": "Odin",
        "numbers": [8, 5, "A", 3],
        "element": Element.NONE,
        "level": 9,
    },
    {
        "id": 93,
        "name": "Pandemona",
        "numbers": ["A", 7, 1, 7],
        "element": Element.WIND,
        "level": 9,
    },
    {
        "id": 94,
        "name": "Cerberus",
        "numbers": [7, "A", 4, 6],
        "element": Element.NONE,
        "level": 9,
    },
    {
        "id": 95,
        "name": "Alexander",
        "numbers": [9, 2, "A", 4],
        "element": Element.HOLY,
        "level": 9,
    },
    {
        "id": 96,
        "name": "Phoenix",
        "numbers": [7, "A", 2, 7],
        "element": Element.FIRE,
        "level": 9,
    },
    {
        "id": 97,
        "name": "Bahamut",
        "numbers": ["A", 6, 8, 2],
        "element": Element.NONE,
        "level": 9,
    },
    {
        "id": 98,
        "name": "Doomtrain",
        "numbers": [3, "A", 1, "A"],
        "element": Element.POISON,
        "level": 9,
    },
    {
        "id": 99,
        "name": "Eden",
        "numbers": [4, "A", 4, 9],
        "element": Element.NONE,
        "level": 9,
    },
    {
        "id": 100,
        "name": "Ward",
        "numbers": ["A", 8, 7, 2],
        "element": Element.NONE,
        "level": "A",
    },
    {
        "id": 101,
        "name": "Kiros",
        "numbers": [6, "A", 7, 6],
        "element": Element.NONE,
        "level": "A",
    },
    {
        "id": 102,
        "name": "Laguna",
        "numbers": [5, 9, "A", 3],
        "element": Element.NONE,
        "level": "A",
    },
    {
        "id": 103,
        "name": "Selphie",
        "numbers": ["A", 4, 8, 6],
        "element": Element.NONE,
        "level": "A",
    },
    {
        "id": 104,
        "name": "Quistis",
        "numbers": [9, 2, 6, "A"],
        "element": Element.NONE,
        "level": "A",
    },
    {
        "id": 105,
        "name": "Irvine",
        "numbers": [2, "A", 6, 9],
        "element": Element.NONE,
        "level": "A",
    },
    {
        "id": 106,
        "name": "Zell",
        "numbers": [8, 6, 5, "A"],
        "element": Element.NONE,
        "level": "A",
    },
    {
        "id": 107,
        "name": "Rinoa",
        "numbers": [4, "A", "A", 2],
        "element": Element.NONE,
        "level": "A",
    },
    {
        "id": 108,
        "name": "Edea",
        "numbers": ["A", 3, "A", 3],
        "element": Element.NONE,
        "level": "A",
    },
    {
        "id": 109,
        "name": "Seifer",
        "numbers": [6, 4, 9, "A"],
        "element": Element.NONE,
        "level": "A",
    },
    {
        "id": 110,
        "name": "Squall",
        "numbers": ["A", 9, 4, 6],
        "element": Element.NONE,
        "level": "A",
    },
    {
        "id": 111,
        "name": "hidden_card",
        "numbers": ["A", "A", "A", "A"],
        "element": Element.NONE,
        "level": "A",
    },
]